# Generated by Django 5.2.6 on 2025-09-04 15:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Введите адрес электронной почты', max_length=254, unique=True, verbose_name='Email')),
                ('country', models.CharField(db_index=True, help_text='Введите страну', max_length=140, verbose_name='Страна')),
                ('city', models.CharField(db_index=True, help_text='Введите город', max_length=140, verbose_name='Город')),
                ('street', models.CharField(help_text='Введите улицу', max_length=140, verbose_name='Улица')),
                ('house_number', models.CharField(help_text='Введите номер дома', max_length=20, verbose_name='Номер дома')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ['city', 'street', 'house_number'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(help_text='Введите название оборудования', max_length=280, verbose_name='Название оборудования')),
                ('equipment_model', models.CharField(help_text='Введите наименование модели оборудования', max_length=280, verbose_name='Тип (модель) оборудования')),
                ('market_release_date', models.DateField(help_text='Укажите дату выхода на рынок', verbose_name='Дата выхода на рынок')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'ordering': ['equipment_name', 'equipment_model'],
            },
        ),
        migrations.CreateModel(
            name='SaleNet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_name', models.CharField(max_length=200, verbose_name='Название')),
                ('arrears', models.DecimalField(decimal_places=3, default=0, help_text='Укажите задолженность перед поставщиком (неотрицательное число)', max_digits=28, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Задолженность перед поставщиком')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('equipments', models.ManyToManyField(to='electronics_sales.equipment', verbose_name='Оборудование')),
                ('net_contacts', models.OneToOneField(help_text='Укажите контакт', on_delete=django.db.models.deletion.CASCADE, related_name='sale_net', to='electronics_sales.contact', verbose_name='Контакты')),
                ('supplier', models.ForeignKey(blank=True, help_text='Укажите поставщика', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='electronics_sales.salenet', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Сеть продаж',
                'verbose_name_plural': 'Сети продаж',
                'ordering': ['net_name'],
            },
        ),
    ]
