# Generated by Django 5.2.6 on 2025-09-04 23:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics_sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salenet',
            options={},
        ),
        migrations.AlterField(
            model_name='equipment',
            name='market_release_date',
            field=models.DateField(blank=True, help_text='Укажите дату выхода на рынок', null=True, verbose_name='Дата выхода на рынок'),
        ),
        migrations.AlterField(
            model_name='salenet',
            name='arrears',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Укажите задолженность перед поставщиком (неотрицательное число)', max_digits=28, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Задолженность перед поставщиком'),
        ),
        migrations.AlterField(
            model_name='salenet',
            name='equipments',
            field=models.ManyToManyField(blank=True, related_name='salenets', to='electronics_sales.equipment', verbose_name='Оборудование'),
        ),
        migrations.AlterField(
            model_name='salenet',
            name='net_contacts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salenets', to='electronics_sales.contact'),
        ),
        migrations.AlterField(
            model_name='salenet',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='electronics_sales.salenet'),
        ),
        migrations.AddIndex(
            model_name='salenet',
            index=models.Index(fields=['net_name'], name='electronics_net_nam_84e53e_idx'),
        ),
    ]
